[package]
name = "openbsd-version"
version = "0.3.0"
authors = ["flipchan <flipchan[at]riseup.net>"]
edition = "2018"
publish = false


[dependencies]
regex = "1.3.6"
chrono = "0.4.11"
pledge = "0.4.0"
